### ISSUE TITLE
If you recreate homepage

### ISSUE THREAD

**Issue by RyosukeCla** [meioke/meiokeWeb#1]
Currently, probably, when you change contents, you directly change the code of contents in html. This is called "Hard coding". If you want to manage contents on your website, I think you should recreate website with web technology. Today, there are a lot of great libraries and frameworks to create  from desktop application to web application with web technology. 
At first, if you chose to remake it, you have to consider about what your target website needs. And then, you need to decide which technology you need to remake.

I show u a little. I think your website needs several functions below.

- Update contents without hard coding.
- Anyone can manage contents with no complexities.
- Nice front side.

I know some ways to implement these.

1. Use web service like ameba, hatena.
2. Use CMS like wordpress.
3. Use web framework like rails, laravel.

First option is super easy to remake your website with comparably nice front and you don't have to think about any technologies. But you cannot add new features and change front side.
Second option is easy to launch your website if you have knowledge of deploying web service. It has fluent system so you can add new functions and change front side. But these tasks are boring because you have to understand the system inside of CMS you chose.
I recommend final option because to understand web tech is very fun and you can create a web with your own idea. It will take a lot of times to dive in to web tech, though.

If you chose 3rd option, I can advice you how to make or which tech you need.

**Comment by m4sks** [comment]
Thank u for your comment. 
I know this is the "hard cording". So I'll stop to use it in the near future, but updating of the website was necessary for our group's management (cuz new students are coming). I want you to understand. 

Anyway, I planned to use wordpress like as your 2nd option. but after your comment, I’m wavering. 
To be frank, in addition to recreate website understanding the web tech is ideal. and If you give me some advice, your 3rd option will be possible. Problem is there’s not much time to spring. As I said, new students are coming, and we should recreate website immediately to invite them. (or complete in time for next year)
